### ISSUE TITLE
docu refers still to `duckdb/append-dataset!`

### ISSUE THREAD

**Issue by behrica** [techascent/tmducken#1]
https://github.com/cnuernber/tmducken/blob/cec835ca1c4f79d54f44ec948b423ac64643f32e/src/tmducken/duckdb.clj#L32

While it seems to be called `insert-dataset!`:
https://github.com/cnuernber/tmducken/blob/cec835ca1c4f79d54f44ec948b423ac64643f32e/src/tmducken/duckdb.clj#L258

Same in comment:
https://github.com/cnuernber/tmducken/blob/cec835ca1c4f79d54f44ec948b423ac64643f32e/src/tmducken/duckdb.clj#L472

**Comment by cnuernber** [comment]
Great find :-)

**Comment by cnuernber** [comment]
Done!
