### ISSUE TITLE
Use binary from jdbc driver jar?

### ISSUE THREAD

**Issue by jdf-id-au** [techascent/tmducken#13]
Thanks for this project (incl the hilarious name).

Instead of manually providing the binary, would it be possible [somehow to make use of](https://stackoverflow.com/questions/20389255/reading-a-resource-file-from-within-jar) the one in the [jdbc jar file](https://mvnrepository.com/artifact/org.duckdb/duckdb_jdbc)  (like `libduckdb_java.so_linux_amd64`), or is that a different thing? That would make deployment etc easier.

I'm happy to have a fiddle if I'm barking up the right tree.

**Comment by cnuernber** [comment]
It should be possible, sure.  We should look at how the jdbc driver loads the binary

**Comment by cnuernber** [comment]
This is now partially addressed by the nix pathway.
