### ISSUE TITLE
Sql->ds does return column names as string

### ISSUE THREAD

**Issue by awb99** [techascent/tmducken#14]
Thia is not really a big deal.
But appending datasets works with column names being keywords.
Running sql->ds returns column names as string.

Its counterituitive when I can create a new table and append data with columns that are keywords. But when querying it gives back string names.

**Comment by cnuernber** [comment]
key-fn is an option here so just like parsing a CSV - :key-fn keyword will do what you expect.  In fact many of the standard parsing options are available here.

**Comment by awb99** [comment]
oh very nice! Perhaps you want to add this to the docs. Because I didnt see this option anywhere.
