### ISSUE TITLE
At some point, redirect people to the techascent fork

### ISSUE THREAD

**Issue by harold** [techascent/tmducken#4]
https://github.com/techascent/tmducken/

I guess replace the readme here with that link? Or, what's the procedure?

**Comment by cnuernber** [comment]
Yes let's move things to techascent fork and release tmducken under com.techascent/tmducken.

**Comment by harold** [comment]
Quick thought here, the version number could match duckdb, so something like `0.8.1-01`...

**Comment by cnuernber** [comment]
Transfered ownership

**Comment by harold** [comment]
:+1: :+1:
