### ISSUE TITLE
UUID type support

### ISSUE THREAD

**Issue by harold** [techascent/tmducken#9]
Looks like DuckDB supports UUIDs: https://duckdb.org/docs/sql/data_types/overview.html

It'd be rad if this worked:

```clojure
user> (require '[tmducken.duckdb :as duckdb])
nil
user> (duckdb/initialize!)
Sep 07, 2023 10:15:27 AM clojure.tools.logging$eval9329$fn__9332 invoke
INFO: Attempting to load duckdb from "./binaries/libduckdb.so"
true
user> (require '[tech.v3.dataset :as ds])
nil
user> (def ds (ds/->dataset {"a" [0 0] "b" [(random-uuid) (random-uuid)]}))
#'user/ds
user> (def db (duckdb/open-db))
#'user/db
user> (def conn (duckdb/connect db))
#'user/conn
user> (duckdb/create-table! conn ds)
Execution error at tech.v3.dataset.sql/default-sql-datatype (sql.clj:172).
Failed to find default sql datatype for :uuid
```

Judging from the error, maybe this would get us closer to other things working in Postgres as well?

**Comment by cnuernber** [comment]
Sure - I think postgres supports UUIDs and I may have already added that - there is a database-specific extension mechanism to unify funky per-database types such as UUIDs in tech.ml.dataset.sql.

We should definitely support them here - I know duckdb already does.

**Comment by cnuernber** [comment]
Done - release 12 currently.

**Comment by harold** [comment]
https://github.com/techascent/tmducken/commit/07e6e57b157754906c333fc747a6bd0d91683953
